// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatbotSubscriptionController from "./chatbot_subscription_controller"
application.register("chatbot-subscription", ChatbotSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import NoticeConfirmationController from "./notice_confirmation_controller"
application.register("notice-confirmation", NoticeConfirmationController)
